name: Manual triggered SAST Action
on: [workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - name: build
              run: echo I build
            - name: what do we have
              run: ls -la              
        
    pipeline-scan:
        runs-on: ubuntu-latest
        steps:
            - name: what do we have
              run: ls -la  
              
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                 java-version: 1.8
            
            - name: Download the Pipeline Scanner
              uses: wei/curl@master
              with:
                 args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
            
            - name: Unzip the Pipeline Scanner
              run: unzip pipeline-scan-LATEST.zip
            
            - name: Run Pipeline Scanner
              run: java -jar pipeline-scan.jar --verbose --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --file "bin/verademo.war" --fail_on_severity="Very High, High"
              
